/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DEINT.Vistas;

/**
 *
 * @author mario
 */
public class VentanaDeConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    private int diasPrestamo = 15;
    private int cantidadMaxima = 3;
    private int diasSancion = 30;

    public VentanaDeConfiguracion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        DiasPrestamo = new javax.swing.JLabel();
        CantidadMaxima = new javax.swing.JLabel();
        DiasSancion = new javax.swing.JLabel();
        DiasDeSancion = new javax.swing.JTextField();
        DiasDePrestamo = new javax.swing.JTextField();
        CantidadMax = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuracion.png"))); // NOI18N

        DiasPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        DiasPrestamo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DiasPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        DiasPrestamo.setText("- Días de préstamo:");

        CantidadMaxima.setBackground(new java.awt.Color(255, 255, 255));
        CantidadMaxima.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CantidadMaxima.setForeground(new java.awt.Color(0, 0, 0));
        CantidadMaxima.setText("- Cantidad máxima de libros en préstamo:");

        DiasSancion.setBackground(new java.awt.Color(255, 255, 255));
        DiasSancion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DiasSancion.setForeground(new java.awt.Color(0, 0, 0));
        DiasSancion.setText("- Días de sanción por retraso en la devolución:");

        DiasDeSancion.setEditable(false);
        DiasDeSancion.setText("30");
        DiasDeSancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasDeSancionActionPerformed(evt);
            }
        });

        DiasDePrestamo.setEditable(false);
        DiasDePrestamo.setText("15");
        DiasDePrestamo.setToolTipText("");
        DiasDePrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasDePrestamoActionPerformed(evt);
            }
        });

        CantidadMax.setEditable(false);
        CantidadMax.setText("5");
        CantidadMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CantidadMaxima)
                                .addGap(18, 18, 18)
                                .addComponent(CantidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiasPrestamo)
                                .addGap(18, 18, 18)
                                .addComponent(DiasDePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiasSancion)
                                .addGap(18, 18, 18)
                                .addComponent(DiasDeSancion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Icono)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiasPrestamo)
                    .addComponent(DiasDePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadMaxima)
                    .addComponent(CantidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiasSancion)
                    .addComponent(DiasDeSancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DiasDePrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasDePrestamoActionPerformed
        // TODO add your handling code here:
        DiasDePrestamo.setText(Integer.toString(diasPrestamo));
        DiasDePrestamo.setEditable(false);
    }//GEN-LAST:event_DiasDePrestamoActionPerformed

    private void CantidadMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadMaxActionPerformed
        // TODO add your handling code here:
        CantidadMax.setText(Integer.toString(cantidadMaxima));
        CantidadMax.setEditable(false);
    }//GEN-LAST:event_CantidadMaxActionPerformed

    private void DiasDeSancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasDeSancionActionPerformed
        // TODO add your handling code here:
        DiasDeSancion.setText(Integer.toString(diasSancion));
        DiasDeSancion.setEditable(false);
    }//GEN-LAST:event_DiasDeSancionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadMax;
    private javax.swing.JLabel CantidadMaxima;
    private javax.swing.JTextField DiasDePrestamo;
    private javax.swing.JTextField DiasDeSancion;
    private javax.swing.JLabel DiasPrestamo;
    private javax.swing.JLabel DiasSancion;
    private javax.swing.JLabel Icono;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
