/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DEINT.Libreria;

import DEINT.Funcionamiento.*;
import DEINT.Vistas.*;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author mario
 */
public class AppBiblioteca extends javax.swing.JFrame {

    Biblioteca miBiblioteca = new Biblioteca();

    public Biblioteca getMiBiblioteca() {
        return miBiblioteca;
    }

    /**
     * Creates new form NewJFrame
     */
    public AppBiblioteca() {
        initComponents();
        initStyle();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroun = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Inicio = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        Prestamo = new javax.swing.JButton();
        Devolucion = new javax.swing.JButton();
        Catalogo = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Barra = new javax.swing.JPanel();
        GitHubTexto = new javax.swing.JLabel();
        emailTexto = new javax.swing.JLabel();
        textoEjercicio = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1036, 652));

        backgroun.setPreferredSize(new java.awt.Dimension(1020, 640));

        menu.setBackground(new java.awt.Color(66, 38, 84));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Inicio.setBackground(new java.awt.Color(66, 38, 84));
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magia.png"))); // NOI18N
        Inicio.setBorder(null);
        Inicio.setBorderPainted(false);
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        Configuracion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuracion.png"))); // NOI18N
        Configuracion.setText("Configuración");
        Configuracion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Configuracion.setBorderPainted(false);
        Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Configuracion.setIconTextGap(10);
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });

        Prestamo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Prestamo.setForeground(new java.awt.Color(255, 255, 255));
        Prestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito-de-compras_1.png"))); // NOI18N
        Prestamo.setText("Prestamo");
        Prestamo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Prestamo.setBorderPainted(false);
        Prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prestamo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Prestamo.setIconTextGap(10);
        Prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamoActionPerformed(evt);
            }
        });

        Devolucion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Devolucion.setForeground(new java.awt.Color(255, 255, 255));
        Devolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro_1.png"))); // NOI18N
        Devolucion.setText("Devolucion");
        Devolucion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Devolucion.setBorderPainted(false);
        Devolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Devolucion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Devolucion.setIconTextGap(10);
        Devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucionActionPerformed(evt);
            }
        });

        Catalogo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Catalogo.setForeground(new java.awt.Color(255, 255, 255));
        Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca-en-linea_1.png"))); // NOI18N
        Catalogo.setText("Catalogo");
        Catalogo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Catalogo.setBorderPainted(false);
        Catalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Catalogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Catalogo.setIconTextGap(10);
        Catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogoActionPerformed(evt);
            }
        });

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de-miedo_1.png"))); // NOI18N
        Usuario.setText("Usuario");
        Usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Usuario.setBorderPainted(false);
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Usuario.setIconTextGap(10);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Inicio))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Inicio)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Barra.setBackground(new java.awt.Color(214, 178, 237));
        Barra.setPreferredSize(new java.awt.Dimension(750, 90));

        GitHubTexto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GitHubTexto.setForeground(new java.awt.Color(255, 255, 255));
        GitHubTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/github.png"))); // NOI18N
        GitHubTexto.setText("marromagu");
        GitHubTexto.setIconTextGap(10);

        emailTexto.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        emailTexto.setForeground(new java.awt.Color(255, 255, 255));
        emailTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informacion_1.png"))); // NOI18N
        emailTexto.setText(" UD_3_DI_Mario_RomeroAguilar.");

        textoEjercicio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textoEjercicio.setForeground(new java.awt.Color(255, 255, 255));
        textoEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gmail_1.png"))); // NOI18N
        textoEjercicio.setText("mromagu2611@g.educaand.es");
        textoEjercicio.setIconTextGap(10);

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(GitHubTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(textoEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(emailTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTexto)
                    .addComponent(textoEjercicio)
                    .addComponent(GitHubTexto))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(0, 490));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        texto.setText("Mario Romero Aguilar");

        javax.swing.GroupLayout backgrounLayout = new javax.swing.GroupLayout(backgroun);
        backgroun.setLayout(backgrounLayout);
        backgrounLayout.setHorizontalGroup(
            backgrounLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrounLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrounLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrounLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
        );
        backgrounLayout.setVerticalGroup(
            backgrounLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(backgrounLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgrounLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgrounLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgrounLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                    .addGroup(backgrounLayout.createSequentialGroup()
                        .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroun, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroun, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucionActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDeDevolucion());
    }//GEN-LAST:event_DevolucionActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDeConfiguracion());
    }//GEN-LAST:event_ConfiguracionActionPerformed

    private void PrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestamoActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDePrestamos());
    }//GEN-LAST:event_PrestamoActionPerformed

    private void CatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogoActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDeCatalogo());
    }//GEN-LAST:event_CatalogoActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDeUsuario());
    }//GEN-LAST:event_UsuarioActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new VentanaDeInicio());
    }//GEN-LAST:event_InicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatAtomOneDarkIJTheme.setup();
        //UIManager.put("Button.arc", 999);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JButton Catalogo;
    private javax.swing.JButton Configuracion;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton Devolucion;
    private javax.swing.JLabel GitHubTexto;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Prestamo;
    private javax.swing.JButton Usuario;
    private javax.swing.JPanel backgroun;
    private javax.swing.JLabel emailTexto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel textoEjercicio;
    // End of variables declaration//GEN-END:variables

    private void initStyle() {
        texto.putClientProperty("FlatLaf.styleClass", "h1");
        texto.setForeground(Color.WHITE);
    }

    private void InitContent() {
        VentanaDeInicio miInicio = new VentanaDeInicio();
        miInicio.setSize(750, 430);
        miInicio.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(miInicio, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();

    }

    private void ShowJPanel(JPanel p) {
        p.setSize(700, 400);
        p.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(p, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }
}
